name: blindtestlol_flutter_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flare_flutter: ^3.0.2
  image: ^4.1.7
  video_player: ^2.8.7
  cupertino_icons: ^1.0.6
  audioplayers: ^6.0.0
  circular_countdown_timer: ^0.2.3
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/song/
    - assets/images/
    - assets/images/legendes/
    - assets/images/backgrounds/
    - assets/images/esgi/
    - assets/images/logo/
    - assets/images/gif/
    - assets/musicBackground/
  fonts:
    - family: CustomFont1
      fonts:
        - asset: lib/utils/font/BeaufortforLOL-OTF/BeaufortforLOL-Bold.otf
    - family: CustomFont2
      fonts:
        - asset: lib/utils/font/Spiegel-OTF/Spiegel-Bold.otf
    # Ajoutez d'autres fichiers de police selon vos besoins
